# Sprint 3 - Manipulación de Datos I (Ejercicios)

En los ejercicios a continuación se busca practicar los fundamentos de manipulación de datos con **Tidyverse**, a fin de fortalecer tus habilidades técnicas en funciones y métodos de esta librería. En concreto revisarás los siguientes temas:

* Carga y entendimiento de datos.
* Tratamiento de valores ausentes.
* Tratamiento de duplicados.
* Filtrado por indexación.
* Filtrado por consulta.
* Agrupamiento de datos.

## Carga y entendimiento de datos

### Ejercicio 1

Importa la librería **Tidyverse** y carga el dataset [**autos_ws.csv**](https://raw.githubusercontent.com/jsaraujo5081/material_curso_data_analytics/refs/heads/main/datasets/autos_ws.csv).

In [1]:
# Cargar libreria
library(tidyverse)

# Cargar datos
df = read_csv("https://raw.githubusercontent.com/jsaraujo5081/material_curso_data_analytics/refs/heads/main/datasets/autos_ws.csv")

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Rows: 177185 Columns: 16
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (6): VehicleType, Gearbox, Model, FuelType, Brand, NotRepaired
dbl (10): DateCrawled, Price, RegistrationYear, Power, Kilometer, Registrati...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Ejercicio 2

Muestra la información de la estructura y las características generales del dataset.

In [2]:
glimpse(df)

Rows: 177,185
Columns: 16
$ DateCrawled       <dbl> 42453.49, 42443.54, 42460.73, 42461.87, 42464.99, 42…
$ Price             <dbl> 480, 9800, 3600, 2200, 14500, 2000, 999, 17999, 300,…
$ VehicleType       <chr> NA, "suv", "small", "convertible", "bus", "sedan", "…
$ RegistrationYear  <dbl> 1993, 2004, 2008, 2004, 2014, 2004, 1995, 2011, 2016…
$ Gearbox           <chr> "manual", "auto", "manual", "manual", "manual", "man…
$ Power             <dbl> 0, 163, 69, 109, 125, 105, 115, 190, 60, 136, 160, 9…
$ Model             <chr> "golf", "grand", "fabia", "2_reihe", "c_max", "3_rei…
$ Kilometer         <dbl> 150000, 125000, 90000, 150000, 30000, 150000, 150000…
$ RegistrationMonth <dbl> 0, 8, 7, 8, 8, 12, 11, 3, 0, 6, 4, 5, 10, 4, 1, 1, 2…
$ FuelType          <chr> "petrol", "gasoline", "gasoline", "petrol", "petrol"…
$ Brand             <chr> "volkswagen", "jeep", "skoda", "peugeot", "ford", "m…
$ NotRepaired       <chr> NA, NA, "no", "no", NA, "no", NA, "no", NA, "no", "n…
$ DateCreated       <dbl> 42453, 42443, 42460, 42461, 42464, 42455, 42444, 424…
$ NumberOfPictures  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ PostalCode        <dbl> 70435, 90480, 60437, 67112, 94505, 96224, 37269, 417…
$ LastSeen          <dbl> 42467.14, 42465.53, 42466.43, 42465.76, 42464.99, 42…

Imprime una muestra aleatoria de 10 elementos del dataset.

In [3]:
df %>%
sample_n(size = 10)

   DateCrawled Price VehicleType RegistrationYear Gearbox Power Model
1  42434.60     2400 sedan       2000             manual  101   a4
2  42465.56     2590 convertible 2001             manual  136   2_reihe
3  42455.91     3800 NA          2018             manual    0   kangoo
4  42453.62     1450 small       1999             manual   90   golf
5  42449.54     1300 small       1995             manual   45   polo
6  42463.82    13200 convertible 2008             auto    140   eos
7  42460.71     2199 small       2005             manual   71   other
8  42439.66     5800 wagon       2005             auto    140   a4
9  42438.95    13500 sedan       2008             manual  177   3er
10 42456.83    13990 sedan       2007             auto    232   a6
   Kilometer RegistrationMonth FuelType Brand      NotRepaired DateCreated
1  150000     0                petrol   audi       NA          42433
2  100000     2                petrol   peugeot    no          42465
3  150000     0                gasoline renault    NA          42455
4  150000     0                petrol   volkswagen NA          42453
5  150000     7                petrol   volkswagen no          42449
6   80000     3                gasoline volkswagen no          42463
7   50000     8                petrol   suzuki     NA          42460
8  150000     6                gasoline audi       no          42439
9  100000     8                gasoline bmw        no          42438
10 150000    10                gasoline audi       no          42456
   NumberOfPictures PostalCode LastSeen
1  0                56070      42466.24
2  0                56410      42465.56
3  0                23795      42466.55
4  0                47058      42467.28
5  0                65618      42453.33
6  0                68163      42465.84
7  0                31832      42464.43
8  0                73479      42440.14
9  0                90513      42439.70
10 0                52428      42456.83

### Ejercicio 3

Verifica los valores únicos existentes en las columnas VehicleType y Gearbox.

In [4]:
# Verificar valores de VehicleType
df["VehicleType"] %>%
unique()

  VehicleType
1 NA
2 suv
3 small
4 convertible
5 bus
6 sedan
7 wagon
8 coupe
9 other

In [5]:
# Verificar valores de Gearbox
df["Gearbox"] %>%
unique()

  Gearbox
1 manual
2 auto
3 NA

## Tratamiento de valores ausentes

### Ejercicio 1

Has un conteo de los valores ausentes que existen en cada una de las columnas del dataset.

In [6]:
print(colSums(is.na(df)))

      DateCrawled             Price       VehicleType  RegistrationYear
                0                 0             18717                 0
          Gearbox             Power             Model         Kilometer
             9765                 0              9865                 0
RegistrationMonth          FuelType             Brand       NotRepaired
                0             16362                 0             35591
      DateCreated  NumberOfPictures        PostalCode          LastSeen
                0                 0                 0                 0

### Ejercicio 2

Imputa en los valores ausentes de la columna VehicleTipe el valor modal.

In [7]:
# Calcular la moda
moda <- df %>%
count(VehicleType) %>%
arrange(desc(n)) %>%
slice_head(n = 1) %>%
pull(VehicleType)

# Asignar moda a valores perdidos
df <- df %>%
mutate(VehicleType = if_else(
    is.na(VehicleType),
    moda,
    VehicleType
))

print(colSums(is.na(df)))

      DateCrawled             Price       VehicleType  RegistrationYear
                0                 0                 0                 0
          Gearbox             Power             Model         Kilometer
             9765                 0              9865                 0
RegistrationMonth          FuelType             Brand       NotRepaired
                0             16362                 0             35591
      DateCreated  NumberOfPictures        PostalCode          LastSeen
                0                 0                 0                 0

### Ejercicio 3

Imputa en los valores ausentes del resto de columnas la expresión "not defined".

In [8]:
df <- df %>%
mutate(Gearbox = if_else(
    is.na(Gearbox),
    "not defined",
    Gearbox
)) %>%
mutate(Model = if_else(
    is.na(Model),
    "not defined",
    Model
)) %>%
mutate(FuelType = if_else(
    is.na(FuelType),
    "not defined",
    FuelType
)) %>%
mutate(NotRepaired = if_else(
    is.na(NotRepaired),
    "not defined",
    NotRepaired
))

print(colSums(is.na(df)))

      DateCrawled             Price       VehicleType  RegistrationYear
                0                 0                 0                 0
          Gearbox             Power             Model         Kilometer
                0                 0                 0                 0
RegistrationMonth          FuelType             Brand       NotRepaired
                0                 0                 0                 0
      DateCreated  NumberOfPictures        PostalCode          LastSeen
                0                 0                 0                 0

## Tratamiento de duplicados

### Ejercicio 1

Identifica si existen filas duplicadas en el dataset.

In [9]:
print(sum(duplicated(df)))

[1] 1

Muestra las filas que estén duplicadas.

In [10]:
df %>%
filter(duplicated(.))

  DateCrawled Price VehicleType RegistrationYear Gearbox Power Model Kilometer
1 42457.04    1000  small       2002             manual  83    other 150000
  RegistrationMonth FuelType Brand  NotRepaired DateCreated NumberOfPictures
1 1                 petrol   suzuki no          42457       0
  PostalCode LastSeen
1 66589      42457.37

### Ejercicio 2

Elimina los valores duplicados existentes.

In [11]:
df <- df %>%
filter(!duplicated(.))

print(sum(duplicated(df)))

[1] 0

## Filtrado por indexación

### Ejercicio 1

Filtra las primeras 7 filas del dataset.

In [12]:
df[1:7,]

  DateCrawled Price VehicleType RegistrationYear Gearbox Power Model
1 42453.49      480 sedan       1993             manual    0   golf
2 42443.54     9800 suv         2004             auto    163   grand
3 42460.73     3600 small       2008             manual   69   fabia
4 42461.87     2200 convertible 2004             manual  109   2_reihe
5 42464.99    14500 bus         2014             manual  125   c_max
6 42455.83     2000 sedan       2004             manual  105   3_reihe
7 42444.95      999 wagon       1995             manual  115   passat
  Kilometer RegistrationMonth FuelType Brand      NotRepaired DateCreated
1 150000     0                petrol   volkswagen not defined 42453
2 125000     8                gasoline jeep       not defined 42443
3  90000     7                gasoline skoda      no          42460
4 150000     8                petrol   peugeot    no          42461
5  30000     8                petrol   ford       not defined 42464
6 150000    12                petrol   mazda      no          42455
7 150000    11                petrol   volkswagen not defined 42444
  NumberOfPictures PostalCode LastSeen
1 0                70435      42467.14
2 0                90480      42465.53
3 0                60437      42466.43
4 0                67112      42465.76
5 0                94505      42464.99
6 0                96224      42466.45
7 0                37269      42461.55

Filtra las filas 100 a 105 y las columnas 2 a 5.

In [13]:
df[100:105, 2:5]

  Price VehicleType RegistrationYear Gearbox
1  1350 small       2002             manual
2  1999 sedan       2016             manual
3  1600 sedan       1996             auto
4 18400 wagon       2011             auto
5 12899 wagon       2009             auto
6  2250 small       2001             not defined

### Ejercicio 2

Filtra las últimas 10 filas de las columnas Price, Brand y Power.

In [14]:
df[(dim(df)[1] - 9):dim(df)[1], c("Price", "Brand", "Power")]

   Price Brand         Power
1  1400  opel          125
2  6500  mercedes_benz 145
3  5000  mercedes_benz 260
4   999  renault        95
5  1490  volkswagen     50
6  3999  bmw             3
7  3200  seat          225
8     0  mitsubishi      0
9  1199  smart         101
10 3400  volkswagen    100

## Filtrado por consulta

### Ejercicio 1

Filtra todos los vehículos con un precio superior a 10,100 pero inferior a 10,200 usando la función `filter`.

In [15]:
df %>%
filter(Price > 10100 & Price < 10200)

   DateCrawled Price VehicleType RegistrationYear Gearbox     Power Model
1  42434.87    10199 wagon       2009             auto        177   3er
2  42449.50    10150 sedan       2007             manual      163   3er
3  42461.54    10199 sedan       2007             manual      122   1er
4  42434.70    10199 sedan       2017             manual      143   1er
5  42448.95    10175 sedan       2011             manual      125   astra
6  42444.78    10199 sedan       2016             manual      333   not defined
7  42448.79    10199 sedan       2012             manual      125   leon
8  42450.91    10150 wagon       2010             manual      102   a3
9  42449.48    10199 wagon       2011             manual      122   octavia
10 42458.79    10199 suv         2008             manual      150   qashqai
11 42462.86    10199 sedan       2007             manual      143   1er
12 42454.62    10150 small       2014             manual       73   clio
13 42457.62    10199 sedan       2010             manual      143   1er
14 42450.58    10150 wagon       2009             not defined 114   qashqai
15 42436.49    10180 wagon       2008             auto        231   3er
16 42443.78    10150 sedan       2011             manual      140   astra
17 42456.45    10199 coupe       2005             manual      163   clk
18 42435.98    10199 wagon       2006             auto        163   3er
19 42452.91    10150 sedan       2006             auto        218   3er
20 42438.45    10199 sedan       2006             auto        303   3er
21 42436.73    10150 wagon       2008             auto        179   a6
22 42436.04    10199 sedan       2011             auto         86   golf
23 42461.53    10111 small       2011             manual      101   meriva
24 42451.41    10150 convertible 2005             manual      231   z_reihe
   Kilometer RegistrationMonth FuelType    Brand         NotRepaired
1  150000     6                gasoline    bmw           no
2  150000     4                gasoline    bmw           no
3   90000    12                petrol      bmw           no
4  125000     9                gasoline    bmw           not defined
5   80000     3                gasoline    opel          no
6  150000     0                not defined bmw           yes
7   70000     7                petrol      seat          no
8   90000     8                petrol      audi          no
9  100000     5                petrol      skoda         no
10 125000     3                gasoline    nissan        not defined
11 125000     8                gasoline    bmw           no
12  30000     3                petrol      renault       no
13 125000     3                gasoline    bmw           no
14  90000    12                petrol      nissan        no
15 150000     4                gasoline    bmw           no
16  50000     3                petrol      opel          no
17 100000     6                petrol      mercedes_benz no
18 150000     9                gasoline    bmw           no
19  50000     3                petrol      bmw           no
20 150000     6                gasoline    bmw           no
21 150000    10                gasoline    audi          yes
22  60000     4                petrol      volkswagen    no
23  20000     5                petrol      opel          no
24 150000     5                petrol      bmw           no
   DateCreated NumberOfPictures PostalCode LastSeen
1  42434       0                72587      42465.60
2  42449       0                35789      42460.91
3  42461       0                83301      42467.39
4  42434       0                65197      42466.99
5  42448       0                51427      42450.03
6  42444       0                54516      42466.82
7  42448       0                51597      42467.30
8  42450       0                97855      42467.07
9  42449       0                89347      42449.48
10 42458       0                65203      42459.94
11 42462       0                65197      42466.55
12 42454       0                58239      42466.74
13 42457       0                97493      42466.78
14 42450       0                52525      42466.41
15 42436       0                84347      42467.49
16 42443       0                45127      42450.41
17 42456       0                73730      42467.28
18 42435       0                44141      42441.57
19 42452       0                14641      42452.91
20 42438       0                33613      42465.62
21 42436       0                86159      42441.49
22 42435       0                33129      42456.51
23 42461       0                93093      42467.39
24 42451       0                38106      42463.85

### Ejercicio 2

Filtra todos los vehículos de las marcas "volkswagen" o "skoda" y con potencia mayor o igual a 1,600.

In [16]:
df %>%
filter(Brand %in% c("volkswagen", "skoda") & Power >= 1600)

   DateCrawled Price VehicleType RegistrationYear Gearbox     Power Model
1  42457.83    10900 bus         2009             manual      10520 caddy
2  42450.92      300 wagon       1996             manual       1999 golf
3  42461.08     5400 sedan       2017             manual       2017 transporter
4  42439.94     2500 convertible 1998             manual       7512 golf
5  42457.49     1690 sedan       1999             manual       7544 golf
6  42441.44     4700 bus         1997             manual      10522 transporter
7  42440.74     1700 sedan       2017             manual       9010 not defined
8  42441.42      350 small       1995             manual       5575 polo
9  42458.62      300 small       1997             manual       4700 polo
10 42461.67     2500 bus         2001             manual       2461 transporter
11 42448.58      600 sedan       1997             manual       6006 passat
12 42461.66     8600 other       2007             not defined  3500 other
13 42451.70        0 bus         2006             manual       1700 touran
14 42453.12     1150 sedan       2016             manual       6011 polo
15 42438.96     3200 sedan       2017             manual       1998 transporter
16 42441.37     6299 small       2012             manual       6062 up
17 42461.78     1250 sedan       2017             manual       9011 golf
18 42454.33      900 wagon       1992             auto         1992 touareg
19 42435.37     2800 wagon       1998             manual      11025 passat
20 42454.69        5 bus         2004             manual       2016 not defined
21 42462.66     1250 wagon       2003             auto         1998 passat
   Kilometer RegistrationMonth FuelType    Brand      NotRepaired DateCreated
1  150000     6                gasoline    volkswagen no          42457
2   10000     0                petrol      volkswagen not defined 42450
3  150000     8                gasoline    volkswagen not defined 42460
4  150000     6                not defined volkswagen not defined 42439
5  125000    12                petrol      volkswagen not defined 42457
6  150000     0                gasoline    volkswagen not defined 42441
7  100000     5                petrol      volkswagen no          42440
8  150000     1                petrol      volkswagen yes         42441
9  150000     4                petrol      volkswagen yes         42458
10 150000     9                gasoline    volkswagen not defined 42461
11 150000     7                petrol      volkswagen yes         42448
12 150000    12                not defined volkswagen not defined 42461
13 150000     9                gasoline    volkswagen no          42451
14 150000     5                not defined volkswagen no          42453
15 150000     0                gasoline    volkswagen not defined 42438
16  50000    11                petrol      volkswagen no          42441
17  60000     5                not defined volkswagen no          42461
18 150000     0                not defined volkswagen not defined 42454
19 150000     6                gasoline    volkswagen not defined 42435
20 150000     0                not defined volkswagen no          42454
21   5000    12                gasoline    volkswagen no          42462
   NumberOfPictures PostalCode LastSeen
1  0                36272      42467.12
2  0                32825      42452.24
3  0                10178      42465.05
4  0                68239      42465.64
5  0                22305      42457.49
6  0                87437      42441.44
7  0                99706      42449.10
8  0                29664      42445.35
9  0                13407      42458.65
10 0                61250      42467.47
11 0                16278      42448.58
12 0                30855      42467.58
13 0                57074      42455.76
14 0                49477      42466.82
15 0                45892      42441.84
16 0                58511      42441.41
17 0                34121      42461.78
18 0                 1665      42466.32
19 0                 1665      42458.68
20 0                58515      42457.72
21 0                33719      42466.62

## Agrupamiento de datos

### Ejercicio 1

Muestra el precio promedio, máximo y mínimo para cada tipo de vehículo usando `group_by`.

In [17]:
df %>%
group_by(VehicleType) %>%
summarise(
    mean = mean(Price),
    max = max(Price),
    min = min(Price)
) %>%
ungroup()

  VehicleType mean     max   min
1 bus         5510.593 20000 0
2 convertible 6814.261 20000 0
3 coupe       6065.179 20000 0
4 other       3518.178 19990 0
5 sedan       4058.153 20000 0
6 small       2675.824 20000 0
7 suv         9083.578 20000 0
8 wagon       4889.602 20000 0

### Ejercicio 2

Muestra en una sola tabla resumen el precio promedio, el kilometraje mediano y la cantidad de modelos por marca.

In [18]:
df %>%
group_by(Brand) %>%
summarise(
    price_mean = mean(Price),
    km_med = median(Kilometer),
    q_models = n_distinct(Model)
) %>%
ungroup()

   Brand          price_mean km_med q_models
1  alfa_romeo      3696.028  150000  7
2  audi            6279.700  150000 17
3  bmw             6157.133  150000 11
4  chevrolet       5542.279  100000  6
5  chrysler        3694.549  150000  7
6  citroen         3566.289  150000  8
7  dacia           5871.701   80000  6
8  daewoo          1047.101  150000  6
9  daihatsu        1632.258  125000  8
10 fiat            2735.537  150000 11
11 ford            3150.522  150000 15
12 honda           3667.404  150000  6
13 hyundai         5219.275  125000  6
14 jaguar          6706.716  150000  4
15 jeep            6857.039  150000  5
16 kia             5087.241  125000  8
17 lada            3358.469   60000  5
18 lancia          2277.483  150000  8
19 land_rover      8598.630  150000 10
20 mazda           3647.464  150000  9
21 mercedes_benz   5933.543  150000 19
22 mini            8963.925  100000  5
23 mitsubishi      2903.621  150000  8
24 nissan          3984.510  150000 10
25 opel            2769.162  150000 17
26 peugeot         3119.601  150000  7
27 porsche        11002.006  150000  5
28 renault         2248.072  150000 11
29 rover           1292.052  150000  5
30 saab            3568.629  150000  4
31 seat            3990.155  150000 11
32 skoda           5904.628  150000  8
33 smart           3500.148  100000  5
34 sonstige_autos  4973.327  100000  1
35 subaru          3564.133  150000  6
36 suzuki          3923.567  125000  5
37 toyota          4776.137  150000  9
38 trabant         1674.437   50000  3
39 volkswagen      4380.312  150000 23
40 volvo           4284.242  150000 10